### ISSUE TITLE
Setting tscc plugin output format to iife is sometimes required

### ISSUE THREAD

**Issue by foobardevpro** [theseanl/tscc#106]
Hi.

Please see the demo (has readme): [https://github.com/foobardevpro/tscc-issues-3](https://github.com/foobardevpro/tscc-issues-3)

For some reasons, sometimes I'm required to explicitly set output format to iife, but other times I'm not. I might be missing something.

**Comment by theseanl** [comment]
The current state is that:
If it is a single-module build, that is, `modules` value in `tscc.spec.json` contains a single key, `rollup-plugin-tscc` can output any format. In this case, the plugin does not override `outputOptions.format`, and it is expected for users to explicitly set this option.
However, for many-module builds, it only supports `iife` bundles in order to emulate closure compiler's chunking behavior. It is this case that the plugin overrides `outputOptions.format`. So this is not an issue. I'm open to suggestions about improving this behavior!
