### ISSUE TITLE
TSCC not compatible with typescript 3.7

### ISSUE THREAD

**Issue by amoerie** [theseanl/tscc#142]
Is there a particular reason why the typescript version is defined in the package.json as ~3.6.4? This prevents us from using 3.7, which we very much like to use for its optional chaining features.

**Comment by theseanl** [comment]
`tsickle` has `typescript@~3.6.4` as a peerdependency. Tsickle uses typescript API a lot, and it needs to perform conversion for new features added to typescript so that it makes sense in Closure, so it is susceptible to typescript version changes. When they release a version that support ts 3.7, tscc will be updated to depend on ts 3.7 as well.
