### ISSUE TITLE
Error: Unrecognized file extension

### ISSUE THREAD

**Issue by davidgu** [theseanl/tscc#159]
I received the error `Error: Unrecognized file extension` while trying to integrate the module `countup.js` from npm.

Declaring it in as an external:
```
{
  "external": {
      ...
      "countUp": "CountUp"
   }
}
```
Results in the error `Error: Unrecognized file extension countUp`.

Declaring it with the name of the npm package as follows 
```
{
  "external": {
      ...
      "countup.js": "CountUp"
   }
}
```
results in the error `Module name node_modules.countup.js.dist.countUp.d was not provided as a closure compilation source`

Bizarrely by installing the stub package @types/countup.js everything compiles properly, even though the @types/countup.js module is empty, and VSCode gives the error `Cannot find module countup.js` when importing from this package.

It seems like something strange is going on with the way `tscc` deals with external type files?

**Comment by DrRataplan** [comment]
Just ran into this exact same issue. Turns out that in `packages/tscc/src/external_module_support.ts`, line 40-ish, a path for the glue module is created. It is doing this by determining the filename for the `.d.ts` for the referenced external. However, if no such file is found, the filename is defaulted to the extern name (countup in you case). Because the algorithm only looks in node_modules, it will not find anything if the library does not contain a typings file.

For me, this was fixed by adding a `.d.ts` to my library, but I think a better fix could be to just append a `.js` extension in `external_module_support`. @theseanl What do you think about a fix like this? I could PR this change if you appreciate it?

**Comment by theseanl** [comment]
@davidgu How is the Typescript instance in your end finding types of `countup.js` module? Could you post some way to repro the issue?

> However, if no such file is found

This code path was just added for safety, and I imagined that the Typescript API `.resolveTypeReferenceDirective` would always resolve to the correct type definition file. As @DrRataplan mentioned, I agree that adding `.js` (or `.ts`) would be a good solution, but I’d like to understand first why this code path was taken.

**Comment by theseanl** [comment]
I've just applied the suggested fix. Check with tscc 0.5.1.
