### ISSUE TITLE
Getting it running on our stack

### ISSUE THREAD

**Issue by natew** [theseanl/tscc#224]
Hey, just wondering if you'd be available to help, we're exploring tscc/tsickle and have dove in pretty deep, but I'm running into too many things that I think someone with experience could help.

So far I've gotten forks of it working in some ways, but can't seem to get rollup to play nicely and actually minify. It seems the rollup plugin doesn't actually ever call tsickle in the end?

Basically - would be happy to pay for some time to help look at our repo! We have it all set up so it's pretty easy to see what's going on. Let me know, would love to get this working.

**Comment by theseanl** [comment]
You are right that the rollup plugin does not ever call tsickle. I think it was not very clear in the readme, and I really need to improve the explanation. The point of `rollup-plugin-tscc` is to do code splitting with rollup in the same way that closure compiler would do, so that it produce the same set of output files. I think, if you have not used closure compiler for code splitting before, it may not be so clear what this means. Closure compiler has certain way of doing code splitting which is very different from what other tools do. So if your project does not need code splitting, you may not need this rollup plugin (although it may still help reducing the amount of code you write). I haven't checked this repo recently and it's been a long time since you've posted here, I hope you have by now found the way to make it work on your stack!

**Comment by theseanl** [comment]
Please re-open if you still have question or something does not work!
