### ISSUE TITLE
Error when using `@types/atom`

### ISSUE THREAD

**Issue by aminya** [theseanl/tscc#306]
When I use `@types/atom` in my code I get this error:
```
TSCC: Module name node_modules._types.atom.index.d was not provided as a closure compilation source
```

It seems that tsickle cannot handle `@types` even for Node!
https://github.com/angular/tsickle/issues/299

**Comment by theseanl** [comment]
Even if you are just using `@types/atom` via triple-slash directives, you have to provide it as an external module in the spec file.

Also, you have to declare an extern for `ImportMeta`:
`externs.js`
```js
/** @externs */
/** @interface */
function ImportMeta() {}
```
`tscc.spec.json`
```json
"compilerFlags": {
    "externs": "externs.js"
}
```
See #99 for the reason.

**Comment by aminya** [comment]
Will this solve all the `@types` issues? If so this should be mentioned in the Readme.

**Comment by theseanl** [comment]
If you are talking about `ImportMeta`, this is something that anyone who has experience with closure compiler can logically led to do so. Anyway, I'm sending PR to tsickle so that this is included in a set of externs they provide, and once it's done you won't need to include `ImportMeta` to compile projects depending on `@types/node`.
