### ISSUE TITLE
outputting to just a single file from multiple

### ISSUE THREAD

**Issue by BrianLeishman** [theseanl/tscc#312]
Maybe it's just me, as this seems like something that would be obvious, but for the life of me I can't figure it out.

If I have my tsconfig.json looking like this
```json
{
    "compilerOptions": {
        "alwaysStrict": true,
        "strict": true,
        "sourceMap": true,
        "noImplicitAny": true,
        "outFile": "../public/v2/js/app.js"
    },
    "include": ["ts/*"]
}
```
and run `tsc`, I get one file from all of my ts files in my folder, which is perfect. I can just include this on my website and everything is good. 

But of course, I get an uncompiled js file, which I would love to pass through Closure Compiler with all the type annotations (which is why I'm here), but I can't figure out how at all to use `tscc` to just do the same thing, and take a folder of ts files and make them into one, closure compiler compiled js file. 

How do I need to configure my `tscc.spec.json` to make one "module" out of all of my files?

---

Experimenting with "extraSources" doesn't seem to get me what I think either. If I change my 
```json
    "modules": {
        "app": "ts/main.ts"
    },
```
to
```json
    "modules": {
        "app": {
            "entry": "ts/main.ts",
            "extraSources": ["ts/footer.ts"]
        }
    },
```
I just get `TSCC: File not emitted from tsickle: ts/footer.ts` in the output (and giving the absolute path here doesn't appear to change anything)

**Comment by theseanl** [comment]
I guess that your typescript files are "scripts", not "modules", which means that they do not contain `import` or `export` statements.

Such use case is not supported, tscc works by discovering dependencies by import statements starting from entry modules. `extraSources` is for providing transpiled `js` files.

In order to make it work, I suppose you can first concatenate all the `ts` files and then feed it to tscc, like:
```
"modules": {
    "app": "ts/concatenated.ts"
}
```
