### ISSUE TITLE
target ES2015 combined with external jquery reference throws JSC_REDECLARED_VARIABLE_ERROR

### ISSUE THREAD

**Issue by BrianLeishman** [theseanl/tscc#380]
tscc.spec.json
```json
{
    "modules": {
        "app": ".tscc_temp/app.ts"
    },
    "external": {
        "jquery": "$"
	},
    "prefix": "../../public/v2/js/",
    "compilerFlags": {
        "rewrite_polyfills": true,
        "language_out": "ES5_STRICT",
        "compilation_level": "ADVANCED_OPTIMIZATIONS",
        "use_types_for_optimization": true,
        "output_wrapper": "(function(){%output%})()"
    }
}
```

tsconfig.json
```json
{
    "compilerOptions": {
        "alwaysStrict": true,
        "strict": true,
        "sourceMap": true,
        "noImplicitAny": true,
        "target": "ES2015",
    },
    "include": [
        "ts/*.ts",
    ],
}
```

And then running returns the following output 
```
TSCC: tsickle converts TypeScript modules to Closure modules via CommonJS internally."module" flag is overridden to "commonjs".
TSCC: tsickle uses a custom tslib optimized for closure compiler. importHelpers flag is set.
TS: .tscc_temp/app.ts(111,11): warning TS0: unhandled type flags: Intersection

TS: .tscc_temp/app.ts(132,7): warning TS0: unhandled type flags: Intersection

ClosureCompiler: /domains/aan/v2/.tscc_temp/c8bf3662b5091e49be4d590eb031e02fde0538e36e1889bb0eda455e0527ce38/externs_generated.js:26284:6: ERROR - [JSC_REDECLARED_VARIABLE_ERROR] Illegal redeclared variable: $
  26284| const $ = {};
               ^^^^^^

1 error(s), 0 warning(s)


✖ Closure compiler error
TSCC: Closure compiler has exited with code 1
TSCC: The compilation has terminated with an error.
```

Got here in an attempt to compile to ES5 with closure compiler, but while using async functions, and Closure Compiler can handle the promise polyfill

**Comment by BrianLeishman** [comment]
If I modify tscc to always use var instead of const in its `externs_generated.js` file, I get this error instead 

```
ClosureCompiler: app.js.tsickle:14:0: ERROR - [JSC_GOOG_MODULE_MISPLACED] goog.module() call must be the first statement in a file.
  14| goog.module('app$.ts');
```

**Comment by theseanl** [comment]
The problem is that `@types/jquery` already augments the global scope by adding declarations for global `$` variable, and tscc adds such a declaration too. I guess it is safe to always produce `var` keyword here. Then effectively, it is left to user's discretion not to collide global alias for external modules to those which are already provided with global modules.

Regarding the second error, could you provide more precise reproduction steps?

**Comment by BrianLeishman** [comment]
in `app.js` for my application, this returns that error

```ts
(async () => {
    console.log('hello world!');
})();
```
```
ClosureCompiler: app.js.tsickle:14:0: ERROR - [JSC_GOOG_MODULE_MISPLACED] goog.module() call must be the first statement in a file.
  14| goog.module('app$.ts');
      ^^^^^^^^^^^^^^^^^^^^^^
```
If I drop the `async`, it compiles.

**Comment by theseanl** [comment]
Your `app.ts` must be a "script", not a "module". A script is characterized by an absence of `import` or `export` statements. Typescript prepends a helper function it uses to downlevel `async` functions for "script" files, instead of importing it from `tslib` like what it does for modules.

I am not sure whether there is any situation where using "script" files is necessary. The only use case I can come up with is some `.ts` files where every statement is ambient, but ts helpers are not needed in declarations. I think I should really find a way to detect script files and warn users about it.

**Comment by BrianLeishman** [comment]
Yeah I'm not entirely sure what modules are, I'm just using ts files as the source to js files that get included on a web page, since I've not come across a need for using modules before

**Comment by BrianLeishman** [comment]
I just figured how to treat everything like modules and it works super smoothly, I'd be okay with closing this as I could see to the reason that modules should just be used in the first place

**Comment by theseanl** [comment]
`const`→`var` change will be available in the next version. I've made a separate issue for detecting script files and warning users about it.
