### ISSUE TITLE
Is there a way to not rename imports?

### ISSUE THREAD

**Issue by BrianLeishman** [theseanl/tscc#463]
First, thank you for this repo, we've been running it in production for almost all of our newer code and it's basically exactly the type of thing I've been looking for!

But the question is about possibly disabling (via config or however) the renaming of the imported variables. For example, I have a file that starts with 
```ts
import Swal from 'sweetalert2';
import * as Ladda from 'ladda';
```
And this ends up getting compiled like 
```js
(function(){'use strict';var E=Swal;var G=Ladda; // ...
```
Which is neat for space saving of course, but our specific issue is that all of our modules are compiled into a single file and loaded on every page, although not every page of our app uses every import. Meaning our home page mainly uses essentially no plugins, and doesn't include the files that set the variables that get renamed and our script fails immediately because `Swal` is not defined. 

Currently we're working around this by just including sweetalert2 and Ladda, etc., on the home page (and others) even though they aren't needed and the TS code that uses them never executes.

**Comment by theseanl** [comment]
I see, so currently if those global variables are not available, then the compiled output will produce a `ReferenceError`.

It seems that adding an option to use `window.Swal` or `self.Swal`, instead of directly referencing `Swal` would be viable. Maybe one should provide an option to choose a global namespace among `window`, `self`, `this`, `global`, and ES2020 `globalThis`.

But how about using workarounds such as

 - using `output_wrapper: "(function(Swal, Ladda){%output%})(this.Swal, this.Ladda)"`,
 - or even use some placeholder names for Swal and Ladda, and post-process the compilation output to replace such placeholder names to JavaScript expressions such as `this.Swal`?
 
When external modules are specified in a spec file, tscc actually generates externs which tells closure compiler that such variables actually exist, so the compiler is free to do any transformation to the code assuming that such variables actually exists. And your described use case does not fit into this assumption.

On a side note, the renaming of global variables you are mentioning is not exactly for space saving as I understand, it's rather how closure compiler handles some code patterns in "gluing modules" that tscc generates. In some cases, not renaming global variable names and directly referencing it will have smaller _gzipped_ code size, I don't know why closure compiler do not "inline" those global variable names.

**Comment by BrianLeishman** [comment]
True, I didn't think about those workarounds, I could very easily just define "Swal" and anything else before all of my other scripts and I won't get those errors, I will certainly implement that!
