### ISSUE TITLE
Bundle output name cannot be same as entry name

### ISSUE THREAD

**Issue by foobardevpro** [theseanl/tscc#81]
1. Download [todomvc-master/typescript-react](https://github.com/theseanl/todomvc/tree/master/typescript-react)
2. Run tscc (global cli) in /js -- compiles successfuly (can skip this step).
3. Modify ``tscc.spec.json``: change bundle output name to same name as input. So instead of:
```
{
	"modules": {
		"bundle": "./app.tsx"
	},
	...
```
we do:

```
{
	"modules": {
		"app": "./app.tsx"
	},
	...
```
4. Run tscc -- will fail with this uninformative error:
```
× Closure compiler error
ClosureCompiler: Exited with code 1.
TSCC: 1
TSCC: The compilation has terminated with an error.
```

**Comment by theseanl** [comment]
I have a logic to prevent this; this again looks like to have caused by file path handling specifics of Window. I'll try when I have access to Windows machine.
The uninformative error is from Closure Compiler, it provides no info that the compilation has failed because the output file's name is identical to one of input files. I've beaten by this before too.

**Comment by theseanl** [comment]
Please check with 0.4.4!
